using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Windows.Forms;

namespace LoxStatEdit
{
    public partial class LoxStatFileForm: Form
    {
        const int _valueColumnOffset = 2;
        readonly string[] _args;
        LoxStatFile _loxStatFile;
        IList<LoxStatProblem> _problems;

        public LoxStatFileForm(params string[] args)
        {
            _args = args;
            InitializeComponent();
        }

        private void LoadFile()
        {
            _fileNameTextBox.Text = Path.GetFullPath(_fileNameTextBox.Text);
            _loxStatFile = LoxStatFile.Load(_fileNameTextBox.Text);
            _dataGridView.RowCount = 0;
            var columns = _dataGridView.Columns;
            while(columns.Count > (_valueColumnOffset + 1))
                columns.RemoveAt(columns.Count - 1);
            _fileInfoTextBox.Text = string.Format("{0}: {1} data point(s) á {2} value(s)",
                _loxStatFile.Text, _loxStatFile.DataPoints.Count, _loxStatFile.ValueCount);
            for(int i = 2; i <= _loxStatFile.ValueCount; i++)
            {
                var newColumn = (DataGridViewColumn)columns[_valueColumnOffset].Clone();
                newColumn.HeaderText = string.Format("{0} {1}", newColumn.HeaderText, i);
                columns.Add(newColumn);
            }
            _dataGridView.RowCount = _loxStatFile.DataPoints.Count;
            RefreshProblems();
        }

        private void RefreshProblems()
        {
            _problems = LoxStatProblem.GetProblems(_loxStatFile);
            _problemButton.Enabled = _problems.Any();
        }

        private void ShowProblems()
        {
            MessageBox.Show
            (
                this,
                string.Format
                (
                    "{1} Problems (showing max 50):{0}{2}",
                    Environment.NewLine,
                    _problems.Count,
                    string.Join(Environment.NewLine, _problems.Take(50))
                ),
                Text,
                MessageBoxButtons.OK,
                MessageBoxIcon.Error
            );
        }

        private void BrowseButton_Click(object sender, EventArgs e)
        {
            openFileDialog.FileName = _fileNameTextBox.Text;
            if (openFileDialog.ShowDialog(this) == DialogResult.OK)
                _fileNameTextBox.Text = openFileDialog.FileName;
        }

        private void LoadButton_Click(object sender, EventArgs e)
        {
            LoadFile();
        }

        private void DataGridView_CellValueNeeded(object sender, DataGridViewCellValueEventArgs e)
        {
            try
            {
                var rowIndex = e.RowIndex;
                var dataPoint = _loxStatFile.DataPoints[rowIndex];
                var columnIndex = e.ColumnIndex;
                e.Value = (columnIndex == 0) ? (object)dataPoint.Index :
                    (columnIndex == 1) ? (object)dataPoint.Timestamp :
                    (object)dataPoint.Values[e.ColumnIndex - _valueColumnOffset];
            }
            catch
            {
                e.Value = null;
            }
        }

        private void DataGridView_CellValuePushed(object sender, DataGridViewCellValueEventArgs e)
        {
            var columnIndex = e.ColumnIndex;
            var dataPoint = _loxStatFile.DataPoints[e.RowIndex];
            if(columnIndex == 1)
                dataPoint.Timestamp = Convert.ToDateTime(e.Value);
            else
                dataPoint.Values[columnIndex - _valueColumnOffset] =
                    Convert.ToDouble(e.Value.ToString());
            RefreshProblems();
        }

        private void MainForm_Load(object sender, EventArgs e)
        {
            if((_args != null) && (_args.Length > 0))
            {
                _fileNameTextBox.Text = _args[0];
                LoadFile();
            }
        }

        private void SaveButton_Click(object sender, EventArgs e)
        {
            RefreshProblems();
            if(_problems.Any())
                ShowProblems();
            if(MessageBox.Show(this, "I will not (and can not) take any " +
                "responsibility for any issues of your Loxone installation whatsoever! " +
                "Loxone will most likely not support any issues if you use the files " +
                "generated by this tool either!" +
                "I am just a desparate Loxone user in need of a solution for a problem " +
                "and lucky enough to be a professional coder! " +
                "Loxone did not provide me a full file format documentation and I used " +
                "Hexinator (thank you!) to decode the file format to some degree! " +
                "Would you still like to save the file?",
                "DISCLAIMER! USE AT YOUR OWN RISK!", MessageBoxButtons.YesNo,
                MessageBoxIcon.Warning, MessageBoxDefaultButton.Button2) != DialogResult.Yes)
                return;
            _loxStatFile.FileName = Path.GetFullPath(_fileNameTextBox.Text);
            _loxStatFile.Save();
            MessageBox.Show(this, "Save successful!", Text, MessageBoxButtons.OK, MessageBoxIcon.Information);
        }

        private void ProblemButton_Click(object sender, EventArgs e)
        {
            ShowProblems();
        }

    }
}
